name: dispatch receiver

on:
  repository_dispatch:
    types: [sample_publish]

env:
  RELEASE_VERSION: ${{ github.event.client_payload.version }}

jobs:
  receive:
    runs-on: ubuntu-latest
    steps:
      - name: receive event info
        run: |
          echo "event name: ${{ github.event_name }}"
          echo "release version: ${{ env.RELEASE_VERSION }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: github-actions-receive-dispatch
      - run: |
          pwd
          ls -al
      - name: Checkout github-actions-samples
        uses: actions/checkout@v4
        with:
          repository: y16ra/github-actions-samples
          fetch-depth: 0
          ref: 'refs/tags/${{ env.RELEASE_VERSION }}'
          sparse-checkout: |
            api/sample-api.yaml
          sparse-checkout-cone-mode: false
          path: github-actions-samples
      - run: |
          pwd
          ls -al
      - name: Check sample-api.yaml
        working-directory: github-actions-samples
        run: |
          pwd
          git branch --contains
          git log |grep '^commit' |head -1|awk '{print $2}'
          cd api
          cat sample-api.yaml
      - name: update api version
        uses: mikefarah/yq@master
        with:
          cmd: TAG=${{ env.RELEASE_VERSION }} yq eval -i '.info.version = env(TAG)' github-actions-samples/api/sample-api.yaml
      - run: |
          pwd
          echo "github-actions-samples/api/sample-api.yaml"
          cat github-actions-samples/api/sample-api.yaml
      - name: Copy api spec file to github-actions-receive-dispatch
        run: |
          pwd
          ls -al
          mkdir -p github-actions-receive-dispatch/api
          cp github-actions-samples/api/sample-api.yaml github-actions-receive-dispatch/api/sample-api.yaml
          cat github-actions-receive-dispatch/api/sample-api.yaml
