name: dispatch receiver

on:
  repository_dispatch:
    types: [sample_publish]

jobs:
  receive:
    runs-on: ubuntu-latest
    steps:
      - name: receive event info
        run: |
          echo "event name: ${{ github.event_name }}"
          echo "release version: ${{ github.event.client_payload.version }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: github-actions-receive-dispatch
      - run: |
          pwd
          ls -al
      - name: Checkout github-actions-samples
        uses: actions/checkout@v4
        with:
          repository: y16ra/github-actions-samples
          sparse-checkout: |
            api/sample-api.yaml
          sparse-checkout-cone-mode: false
          path: github-actions-samples
      - run: |
          pwd
          ls -al
      - name: Check github-actions-samples repo
        working-directory: github-actions-samples
        run: |
          pwd
          ls -al
          cd api
          cat sample-api.yaml
      - name: update api version
        uses: mikefarah/yq@master
        with:
          cmd: TAG=${{ github.event.client_payload.version }} yq eval -i '.info.version = env(TAG)' github-actions-samples/api/sample-api.yaml
      - run: |
          pwd
          echo "github-actions-samples/api/sample-api.yaml"
          cat github-actions-samples/api/sample-api.yaml
      - name: Copy api spec file to github-actions-receive-dispatch
        working-directory: github-actions-receive-dispatch
        run: |
          pwd
          ls -al
          mkdir api
          cp github-actions-samples/api/sample-api.yaml ./api/sample-api.yaml
          cat api/sample-api.yaml
